name: Distribute Test wheels

on:
  # Manual run
  workflow_dispatch:

# ensure only a single job is running
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  wheels:
    uses: ./.github/workflows/wheels.yml

  upload_pypi:
    needs: ["wheels"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        # unpack all artifacts into dist/
        path: dist
        merge-multiple: true
    
    - name: Display files
      run: ls -R dist/

    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
